-- https://www.hackerrank.com/challenges/weather-observation-station-5/problem
-- ORACLE SOLUTION

SELECT * FROM (
        SELECT CITY, LENGTH(CITY) FROM STATION WHERE
        LENGTH(CITY) = (SELECT MIN(LENGTH(CITY)) FROM STATION) ORDER BY CITY
        ) WHERE ROWNUM = 1;

SELECT * FROM (
        SELECT CITY, LENGTH(CITY) FROM STATION WHERE
        LENGTH(CITY) = (SELECT MAX(LENGTH(CITY)) FROM STATION) ORDER BY CITY
        ) WHERE ROWNUM = 1;
