-- https://www.hackerrank.com/challenges/salary-of-employees/problem

-- ORACLE SOLUTION

SELECT NAME FROM EMPLOYEE WHERE SALARY > 2000 AND MONTHS < 10 ORDER BY EMPLOYEE_ID;

-- MS SQL Server SOLUTION

SELECT NAME FROM EMPLOYEE WHERE SALARY > 2000 AND MONTHS < 10 ORDER BY EMPLOYEE_ID;
